### ISSUE TITLE
Error: Cannot find module 'eslint-config-standard'

### ISSUE THREAD

**Issue by u3u** [standard/eslint-config-standard#84]
### eslint -v
v4.2.0

### eslint --init
```
? How would you like to configure ESLint?
  Answer questions about your style
❯ Use a popular style guide
  Inspect your JavaScript file(s)
```
```
? Which style guide do you want to follow?
  Google
  Airbnb
❯ Standard
```
```
? What format do you want your config file to be in? (Use arrow keys)
❯ JavaScript
  YAML
  JSON
```

### .eslintrc
``` json
{
  "extends": "standard"
}
```
### run eslint error
```
$ eslint app.js
Cannot find module 'eslint-config-standard'
Referenced from: /xxx/.eslintrc
Error: Cannot find module 'eslint-config-standard'
```

**Comment by FNGR2911** [comment]
Same here. Even I try to install it myself.

Also got some weird files after running eslint --init (=2.2.0, =3.0.0, 3.5.0, etc.).

Running npm -v 5.0.3

**Comment by u3u** [comment]
@FNGR2911 
I know the reason now, because the `es-lint` I implemented is **global** installed, so it looks for the **global** `eslint-config-standard`. **Locally** installed can be executed using **`node_modules/.bin/eslint`**, or the command is written in the `script` option of the package.json file!

**Comment by Dragon-Rider** [comment]
@u3u It worked！Thanks for help!

**Comment by vigneshr23** [comment]
Hey I dont understand what is going on here.
I tried running `eslint --init` but the problem still persists. Can anyone help?

**Comment by fdambrosio** [comment]
I have the same problem using firebase deploy

**Comment by feross** [comment]
To fix this, ensure that `eslint-config-standard` and all the other dependencies listed in the [readme](https://github.com/standard/eslint-config-standard), are all installed locally, or all installed globally.

It's preferred to install all of them locally rather than globally. Check that they're all listed in `package.json`.

**Comment by brok3nDev** [comment]
Same here smh

**Comment by brettz9** [comment]
FWIW, in my case, it was using `eslint-plugin-standard` instead of `eslint-config-standard`...

**Comment by edisoncks** [comment]
In my case, `eslint --init` only added the dependencies to package.json but did not install them. So I have to manually run `npm install` for it to work.

**Comment by begueradj** [comment]
@u3u  How to add node_modules/.bin/eslint to package.json script commands?
I tried:
```
"scripts": {
  "eslint --fix": "node_modules/.bin/eslint --fix"
} 
```

**Comment by Redfish52** [comment]
I had the same problem but I installed _semistandard_ package from here: [https://www.npmjs.com/package/semistandard](url) and it works for me.

**Comment by j3soon** [comment]
For Windows users, try:
```shell
node_modules\.bin\eslint
```

**Comment by daniel2009** [comment]
How to run node_modules/.bin/eslint ? In terminal for MacOS or cmd for Windows? @u3u @j3soon

**Comment by j3soon** [comment]
@daniel2009 When you want to auto fix your errors, you might want to type:

```shell
eslint --fix --ext .js,.vue --ignore-path .gitignore .
```
inside your project root directory.

But instead you should type:
```shell
node_modules/.bin/eslint --fix --ext .js,.vue --ignore-path .gitignore .
```
or on Windows:
```shell
node_modules\.bin\eslint --fix --ext .js,.vue --ignore-path .gitignore .
```

**Comment by GRTO** [comment]
> @daniel2009 When you want to auto fix your errors, you might want to type:
> 
> ```shell
> eslint --fix --ext .js,.vue --ignore-path .gitignore .
> ```
> 
> inside your project root directory.
> 
> But instead you should type:
> 
> ```shell
> node_modules/.bin/eslint --fix --ext .js,.vue --ignore-path .gitignore .
> ```
> 
> or on Windows:
> 
> ```shell
> node_modules\.bin\eslint --fix --ext .js,.vue --ignore-path .gitignore .
> ```

It worked! thanks :)
